# -*- coding: utf-8 -*-
"""linear_regression from_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPDDXcX43sOaVow_zaFXPedO-gZVgJwd

# Importing Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Writing a Linear Regression class in python"""

class MyLR:
  def __init__(self):
    self.m = None
    self.b = None

  def fit(self,X_train,y_train):
    y_mean = y_train.mean()
    x_mean = X_train.mean()
    num = np.sum((X_train - x_mean) * (y_train - y_mean))
    den = np.sum((X_train-x_mean)**2)
    self.m = num/den
    self.b = y_mean - (self.m*x_mean)
    print(self.m)
    print(self.b)

  def predict(self,X_test):
    return (self.m * X_test) + self.b

"""# Loading dummy dataset"""

df = pd.read_csv("placement.csv")

df.head()

X = df['cgpa'].values

y = df['package'].values

"""# Spliting Data into training set and test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

obj = MyLR()

"""# Model Parameters"""

obj.fit(X_train,y_train)

y_pred = obj.predict(X_test)

"""# Measuring Accuracy of the algorithm"""

from sklearn.metrics import r2_score

acc = r2_score(y_test,y_pred)

acc

"""# Comparison with **sklearn**"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train.reshape(-1,1), y_train)

print(lr.coef_)
print(lr.intercept_)

